"""Stable motor boundary shared by local and wireless transports."""

from __future__ import annotations

from typing import Protocol, runtime_checkable

from lampgo.core.hal import MotorStartupState
from lampgo.core.types import DeviceHealth, JointState


@runtime_checkable
class MotorHAL(Protocol):
    """Interface consumed by motion/recording code.

    Transport details deliberately stop here: the motion runtime works in
    calibrated joint degrees whether the ST3215 bus is attached to this PC or
    to the ESP32-P4 head board.
    """

    def connect(self, calibrate: bool = True, *, configure: bool = True) -> None: ...

    def disconnect(self) -> None: ...

    @property
    def is_connected(self) -> bool: ...

    @property
    def startup_state(self) -> MotorStartupState: ...

    @property
    def recovery_required(self) -> bool: ...

    @property
    def recovery_reason(self) -> str | None: ...

    @property
    def supports_remote_recovery(self) -> bool: ...

    @property
    def motor_names(self) -> list[str]: ...

    def read_positions(self) -> JointState: ...

    def write_positions(self, positions: dict[str, float], move_time_ms: int = 0) -> None: ...

    def write_recovery_positions(self, positions: dict[str, float]) -> None: ...

    def read_recovery_start(self) -> dict[str, float]: ...

    def prepare_recovery(self, frames: list[dict[str, float]]) -> dict[str, float]: ...

    def complete_recovery(self) -> None: ...

    def abort_recovery(self) -> None: ...

    def read_health(self) -> DeviceHealth: ...

    def disable_torque(self) -> None: ...

    def enable_torque(self) -> None: ...

    def get_calibration_home(self) -> dict[str, float] | None: ...
